### ISSUE TITLE
Optimized SVG data URI

### ISSUE THREAD

**Issue by nlemoine** [postcss/postcss-url#103]
While working on data URI with SVG, I stumbled upon this article: https://codepen.io/tigt/post/optimizing-svgs-in-data-uris

I noticed you already replaced encoded spaces with real spaces. SVG data URIs could be a little more optimized by replacing some encoded characters as suggested by the article: `%3D`, `%3A`, `%2F` and maybe `%22`. 

These optimizations still provide a very decent browser support (IE 9+).

Let me know if I can help.

**Comment by sergcen** [comment]
@nlemoine it's can be useful,  i'll add this improvement in next minor version

**Comment by nlemoine** [comment]
👍  Thanks for considering the request!

**Comment by sergcen** [comment]
added option `optimizeSvgEncode` option [7.1.0](https://github.com/postcss/postcss-url/releases/tag/7.1.0)
