### ISSUE TITLE
multiple options : inline -> copy

### ISSUE THREAD

**Issue by digitalkaoz** [postcss/postcss-url#113]
hey, i have the following config:

```js
[{
            url: "inline",
            maxSize: 7,
            optimizeSvgEncode: true
}, {
            url: "copy",
            assetsPath: "dist/",
            shrink: 8,
            useHash: true
}]
```

i would expect this plugins tries inline first, and falls through to copy if the size is bigger than 7KB. but it doenst seem to work this way...how can it be solved (with custom options to `copy`)?

**Comment by sergcen** [comment]
HI @digitalkaoz
I think you're right, this should to work as you say 👍 . I will implement this feature in 8.xx release
But now, you can extend `inline` options by `copy` options

```js
{
            url: 'inline',
            maxSize: 7,
            optimizeSvgEncode: true,
            // fallback options
            fallback: 'copy',
            assetsPath: "dist/",
            shrink: 8,
            useHash: true
}
```

**Comment by digitalkaoz** [comment]
yap that worked! thanks
