### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [postcss/postcss-url#147]
Currently, this plugin is not compatible with [PostCSS 8], also because [postcss-import] is not compatible yet. It would be great if you could make these plugins compatible with the latest version.

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0
[postcss-import]: https://github.com/postcss/postcss-import/issues/427

**Comment by bcomnes** [comment]
Here is a link to the migration guide:

Looks easy to get things moved over preliminarily but I (just a user) unfortunately don't have time atm.  Low hanging fruit for anyone else though:

https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by niksy** [comment]
Easiest way is to transfer everything to `Once` method. Do we want that or should we use more performant API? There’s only one walker defined (for declarations), and running tests on that walker produces some errors.
