### ISSUE TITLE
Don't base64 SVG files

### ISSUE THREAD

**Issue by bfred-it** [postcss/postcss-url#18]
[Probably Don’t Base64 SVG](http://css-tricks.com/probably-dont-base64-svg/), they'll come out smaller.

**Comment by MoOx** [comment]
Did you count the number of http requests saved?
Anyway, we should add an option to filter depending on extensions.
So I'm renaming the issue

**Comment by MoOx** [comment]
Regex?
Array of extensions?
Callback?

ALL OF THIS?

**Comment by bfred-it** [comment]
No, no, I don't mean that they shouldn't be inlined! They should, but the encoding is not necessary

**Comment by MoOx** [comment]
Oh my bad. Fixing the title.

**Comment by MoOx** [comment]
I read to quickly sorry :)

**Comment by Steffen185** [comment]
You should have a look at https://github.com/filamentgroup/directory-encoder/blob/master/lib/svg-uri-encoder.js on how to encode SVG files.

**Comment by bfred-it** [comment]
Cool! New release coming soon?

**Comment by MoOx** [comment]
[Released in 1.3.0](https://github.com/postcss/postcss-url/releases/tag/1.3.0)
