### ISSUE TITLE
`#default#VML` should be ignored

### ISSUE THREAD

**Issue by nthtran** [postcss/postcss-url#25]
`#default#VML` should be ignored like absolute urls and data uris because some stylesheets still have to support IE8 e.g. https://github.com/mapbox/mapbox.js/blob/mb-pages/theme/style.css#L825

**Comment by MoOx** [comment]
We can probably extrapolate to all url() that starts with a `#`, don't you think ?

**Comment by nthtran** [comment]
yeah that works too :+1:

**Comment by MoOx** [comment]
Released in 2.0.2
