### ISSUE TITLE
possible feature - New function Url "copy"

### ISSUE THREAD

**Issue by tinchoz49** [postcss/postcss-url#28]
Hi! first at all, great work guys with postcss is a great tool thanks!

I was thinking that maybe we can have another url function that instead of rebase or inline your files, create a copy in our destination folder renamed with a hash name  and rebase using this new name.

what do you think?

**Comment by MoOx** [comment]
You might already be able to do that since url accept a function https://github.com/postcss/postcss-url#url-function
That said I would accept a PR to add a predefined way to easily copy a file.

**Comment by tinchoz49** [comment]
yes, right now i'm using that. But if you accept a PR, tomorrow i'm going try to make one :)

**Comment by MoOx** [comment]
Closed by 9d1119086343e1b6772abbf20b4e2844ea29a43a
