### ISSUE TITLE
Add postcss as a dependency

### ISSUE THREAD

**Issue by cakeinpanic** [postcss/postcss-url#31]
Hello!
I thing you might add `postcss` as project dependency, not devDependency
Cause it is real dependency needed to work)

**Comment by MoOx** [comment]
Will be when when we will use postcss 4.1 api

**Comment by MoOx** [comment]
Closed by ecf6c9089e9a9b739304d516526fd185acee96d0

**Comment by MoOx** [comment]
Released as 3.3.0
