### ISSUE TITLE
Switch to PostCSS Async API

### ISSUE THREAD

**Issue by josh** [postcss/postcss-url#43]
According to the latest PostCSS plugin guidelines, plugins should ["use asynchronous methods when it is possible"](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#22-use-asynchronous-methods-when-it-is-possible). Theres a number of places postcss-url makes blocking FS calls.

* https://github.com/postcss/postcss-url/blob/130b43c9bc1e6f95d2aeb19ae8dcad26fa8f3693/index.js#L239
* https://github.com/postcss/postcss-url/blob/130b43c9bc1e6f95d2aeb19ae8dcad26fa8f3693/index.js#L244
* https://github.com/postcss/postcss-url/blob/130b43c9bc1e6f95d2aeb19ae8dcad26fa8f3693/index.js#L263
* https://github.com/postcss/postcss-url/blob/130b43c9bc1e6f95d2aeb19ae8dcad26fa8f3693/index.js#L306
* https://github.com/postcss/postcss-url/blob/130b43c9bc1e6f95d2aeb19ae8dcad26fa8f3693/index.js#L318
* https://github.com/postcss/postcss-url/blob/130b43c9bc1e6f95d2aeb19ae8dcad26fa8f3693/index.js#L339

In order to clean this up, the postcss plugin API will need to return a Promise which will mark it as async forcing consumers to use `process(css).then(cb)`. This would probably be considered a major backwards incompatible change.

But I think it would be worth while to align to the plugin best practices as this plugin is listed under the official @postcss org.

There could be other benefits besides this cleanup. For one, I think it would be great to support async logic in the custom url function.

``` js
"postcss-url": {
  url: function(url) {
    return asyncCallToComputeAssetMD5(url).then(function(md5) {
      return url + "?" + md5
    })
  }
}
```

I'd be happy to help work on this. But I just wanted to get an idea if this would be a welcome direction.

Thanks!

-

CC: @MoOx @ai

**Comment by simplesmiler** [comment]
+1 for this one.

**Comment by MoOx** [comment]
I think it's time to explode this plugin that is becoming too big...

**Comment by MoOx** [comment]
Feel free to let me know if you publish something so I can deprecated things over here.

**Comment by tinchoz49** [comment]
Hi @MoOx about what you are saying that the plugin is becoming too big...
I made [postcss-copy](https://github.com/geut/postcss-copy) if the community think is ok, we can remove the copy method from postcss-url and reduce the size.

**Comment by MoOx** [comment]
I prefer to deprecate the plugin directly when all features have been exported elsewhere.

**Comment by SleepWalker** [comment]
Hello, @MoOx

if I need Promises support for an `options.url` function may I create a pull request or should I create a separate plugin?

**Comment by MoOx** [comment]
Depends of the size of the change

**Comment by SleepWalker** [comment]
The actual change won't be big, but I will need to rewrite tests to use async api. Is it ok?

**Comment by SleepWalker** [comment]
@MoOx is it a big change 123b311?
The next commit will add promise support for `DeclProcessor`. It should be not so big as 123b311. And, probably, the whole code will be in `fixUrl` function.
