### ISSUE TITLE
Custom Hash Function

### ISSUE THREAD

**Issue by blond** [postcss/postcss-url#44]
I need to use custom hash-function for `useHash: true` option.

To copy images with unique names to a folder I used [borschik](https://github.com/bem/borschik) with [freeze](https://github.com/bem/borschik/blob/master/docs/freeze/freeze.en.md) option. 

[Hash-function in borschik](https://github.com/bem/borschik/blob/master/lib/freeze.js#L70-L94) different from [hash-function in this package](https://github.com/postcss/postcss-url/blob/master/index.js#L320-L323).

Let's do `hashFunction` option?

**By Default:**

``` js
hashFunction: function (contents) {
    return crypto.createHash('sha1')
      .update(contents)
      .digest('hex')
      .substr(0, 16);
}
```

**For borschik:**

``` js
hashFunction: function (contents) {
    return crypto.createHash('sha1')
        .update(contents)
        .digest('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=/g, '')
        .replace(/^[+-]+/g, '');
}
```

**Comment by tadatuta** [comment]
:+1:

**Comment by SwinX** [comment]
:+1:

**Comment by arikon** [comment]
:fire:

**Comment by arikon** [comment]
@blond You should make a PR ;)

**Comment by sipayRT** [comment]
:+1:

**Comment by tadatuta** [comment]
@moox @ben-eb @truesound how can we help to seed up this issue? It's quite important for Yandex!

**Comment by ben-eb** [comment]
How about being able to pass a function to the existing `useHash` option? PR welcome.

**Comment by MoOx** [comment]
Also https://github.com/postcss/postcss-url/issues/43#issuecomment-133676539

**Comment by tinchoz49** [comment]
Hi guys! i created a new plugin to export the ```copy``` method and add new features, one of them is the ability to use a custom has function: https://github.com/geut/postcss-copy

**Comment by tadatuta** [comment]
@tinchoz49 Thank you! We'll give it a try!

**Comment by sergcen** [comment]
Added in v6 release
