### ISSUE TITLE
Process urls inside AlphaImageLoader

### ISSUE THREAD

**Issue by isqua** [postcss/postcss-url#53]
url in this rule isn’t processed now:
```
-filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='shadow.png',sizingMethod=scale);
```

**Comment by MoOx** [comment]
PR welcome

**Comment by isqua** [comment]
Could I send you small refactoring before?

**Comment by MoOx** [comment]
If you feel the need why not :)

**Comment by isqua** [comment]
![refactoring](https://cloud.githubusercontent.com/assets/529247/10377840/32dea3ce-6e0e-11e5-9e7c-27e34c0cf616.gif)

**Comment by MoOx** [comment]
^^
