### ISSUE TITLE
use with grunt-postcss

### ISSUE THREAD

**Issue by gmoulin** [postcss/postcss-url#6]
Hi,

I have an error when I try to use postcss-url inside grunt-postcss.

Here is the code:

``` javascript
postcss: { 
    options: {
        map: true,
        processors: [
            require('postcss-url')({url: 'inline'}).postcss
        ]
    },
    fonts: {
        src: paths.app_css +'fonts.css',
        dest: paths.app_css +'fonts.embeded.css'
    },
}
```

And the result:

``` bash
Running "postcss:fonts" (postcss) task
[D] Task source: C:\projects\sources\refonte\app_vilebrequin_assets\node_modules\grunt-postcss\tasks\postcss.js
Verifying property postcss.fonts exists in config...OK
Files: cartridge/static/default/_refonte/css/fonts.css -> cartridge/static/default/_refonte/css/fonts.embeded.css
Options: diff=false, map, processors=[null], silent=false
Reading cartridge/static/default/_refonte/css/fonts.css...OK
Warning: undefined is not a function Use --force to continue.

Aborted due to warnings.
```

Note the <code>processors=[null]</code>.
Maybe I missed something in my declaration.

Any idea please ?

**Comment by obiSerra** [comment]
Hi, 

the `.postcss` syntax is from the usage section of the   [grunt-postcss](https://github.com/nDmitry/grunt-postcss) github page:

    grunt.initConfig({
      postcss: {
        options: {
          map: true,
          processors: [
            require('autoprefixer-core')({browsers: 'last 1 version'}).postcss,
            require('csswring').postcss
          ]
        },
        dist: {
          src: 'css/*.css'
        }
      }
    });


ps: removing the  `.postcss` worked perfectly

**Comment by ben-eb** [comment]
@obiSerra Fixed in https://github.com/nDmitry/grunt-postcss/commit/600af72af256c3e41cbc6f971f20a07551f2f24d. :smile:

**Comment by MoOx** [comment]
So we can close this ?

**Comment by MoOx** [comment]
Oh lol, already closed :)
