### ISSUE TITLE
how work with gulp-postcss

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-url#63]
```javascript
var postcssPlugins = [
    postcssUrl({
        url: 'copy',
        to: '/test/'
    }),
];
```

Output:
```
postcss-url: /some/path/app.css:4:3: Option `to` of postcss is required, ignoring
```
After testing value result.opts.from and result.opts.to have same values. set up `from` and `to` through option does not change anything. (https://github.com/postcss/postcss-url/blob/master/index.js#L45)

**Comment by MoOx** [comment]
https://github.com/postcss/postcss/blob/master/docs/source-maps.md#postcss-and-source-maps

The "to" is the one from postcss options.
