### ISSUE TITLE
Cannot understand how to use this

### ISSUE THREAD

**Issue by Grawl** [postcss/postcss-url#64]
Maybe more better and obvious documentation?

**Comment by MoOx** [comment]
What do you not understand?
You got an example and an explanation of each option.

**Comment by Grawl** [comment]
I see only strange JS and CSS files here. No solutions.

**Comment by MoOx** [comment]
No solution to what?
What are you expecting?

**Comment by timaschew** [comment]
For me this plugin also not really clear, even if I look into the tests.
Maybe provide some or at least one example in the readme of the input and generated output.

Another question: are there other solutions to solve the same problem, like https://github.com/webpack/url-loader for instance?

**Comment by MoOx** [comment]
> PostCSS plugin to rebase, inline or copy on url().

rebase: adjust url according to source (make sense after postcss-import)
inline: do you really need an explanation?
copy: hum...

postcss-url was made to adjust url after postcss-import so webpack can found asset with file-loader or url-loader.

**Comment by timaschew** [comment]
I also don't understand the postcss-import, but just the part with node_modules
In the readme there is just used a  `atImport()` but where it's defined that the lookup path is node_modules?

**Comment by MoOx** [comment]
You just didn't read the doc.https://github.com/postcss/postcss-import#options

**Comment by timaschew** [comment]
I did, but in the example there is no `root` passed

**Comment by MoOx** [comment]
because option are optional, and it's explained that node_modules is hardcoded.

**Comment by timaschew** [comment]
where it's explained that it's hardcoded?

**Comment by MoOx** [comment]
First thing in the readme of this module.

**Comment by timaschew** [comment]
> To resolve path of an @import rule, it can look into root directory (by default process.cwd()), web_modules, node_modules or local modules.

If you talking about this part, it's really not obvious.
This sounds like the default is `process.cwd()`, but i __can__ also look into other directories for instance __web_modules__ or __node_modules__.

**Comment by MoOx** [comment]
Make a PR with "it will" then :)

**Comment by timaschew** [comment]
Okay I will.
I think I get it now about postcss-url:
Because postcss-import is inline the imported files the url paths would be break if they wouldn't be adjusted.

And another solution would be to avoid use `@import` in your files, instead use `require()` which is resolved by webpack. At least for modules like __normalize.css__ this works

**Comment by MoOx** [comment]
Yeah but as soon as you rely on on some precedences (eg: any sort of variables) you cannot.

**Comment by timaschew** [comment]
You mean a variable which needs to evaluated in an `@import` statement?

**Comment by MoOx** [comment]
Yes.
