### ISSUE TITLE
default options doesn't work for font-awesome with webpack

### ISSUE THREAD

**Issue by timaschew** [postcss/postcss-url#65]
If I use `@import "font-awesome";` I get errors for all the font urls like 
```
ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../../node_modules/node_modules/font-awesome/fonts/fontawesome-webfont.eot in /Users/timaschew/dev/redux-boilerplate/src/styles
 @ ./~/css-loader!./~/postcss-loader!./src/styles/styles.css 6:8418-8511
```

You see that __node_modules__ exists twice in the resolved path, which is wrong.

This is my webpack config:

```js
  module: {
    loaders: [
      {
        test: /\.css/,
        loader: 'style!css!postcss'
      }
    ]
  },
  postcss: function(webpack) {
    return {
      defaults: [
        // handle @import of node_modules and inline them
        // addDependencyTo allow to handle hot reloading for @import'ed files
        require("postcss-import")({ addDependencyTo: webpack }),
        // fix url() of inlined @import'ed files
        require("postcss-url")({}),
      ]
    }
  }
```

If I omit this line `require("postcss-url")({}),` everything is working fine.

**Comment by MoOx** [comment]
Maybe your loader definition should ignore node_modules

**Comment by timaschew** [comment]
Nope, doesn't help.
This would be very strange if this would work, because then I could not do 
a `require('font-awesome/css/font-awesome.css')` anymore.

I assume that postcss-url doesn't make sense with webpack, because webpack is already resolving the url paths before postcss can access them.

Or do you have any example where postss-url is needed and working with webpack?

**Comment by timaschew** [comment]
lol, don't know what happened exactly, I think I deleted my node_modules and install all the modules again and something strange happened before, but now I'm getting this error

```
ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/globals.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/fontawesome-webfont.svg in /Users/timaschew/dev/redux-boilerplate/src/styles
 @ ./~/css-loader!./~/postcss-loader!./src/styles/globals.css 6:8912-8963
```

And it's fixed if I enable postcss-url again.
