### ISSUE TITLE
do not use path.dirname() on undefined

### ISSUE THREAD

**Issue by jonathanong** [postcss/postcss-url#68]
https://github.com/postcss/postcss-url/blob/743190d1adc0a1467784962c5b31fcb3f926e6e1/index.js#L131

this line is breaking my node@6 builds. here's an example: https://travis-ci.org/mgmtio/assets/jobs/126286844

one solution would be to check that `.file` is defined. i'm not sure what it is so i don't know. if it's required, then it's a bug for me

**Comment by MoOx** [comment]
Maybe testing that "decl.source.input.file" value is present is enough? Not sure how it breaks with node 6...

**Comment by jonathanong** [comment]
node 6 just throws if values passed to `path.dirname()` is `undefined` now. before, it didn't throw.

**Comment by MoOx** [comment]
So I guess here https://github.com/postcss/postcss-url/blob/743190d1adc0a1467784962c5b31fcb3f926e6e1/index.js#L130 we could add another condition on input ?

**Comment by jonathanong** [comment]
Yeah I think so

**Comment by MoOx** [comment]
Patch released in 5.1.2

**Comment by jonathanong** [comment]
👍 thanks
