### ISSUE TITLE
Convert basePath to path, optionally accepting an array

### ISSUE THREAD

**Issue by rybon** [postcss/postcss-url#72]
This will bring the behavior in line with `postcss-import` and allows the module to look for URL assets in various locations. Example: `path: [path.resolve(__dirname, 'src'), path.resolve(__dirname, 'node_modules')]`.

Currently only one path can be supplied, which means resources in `node_modules` for example cannot be found.

The option name `path` seems to be more commonly used than `basePath`, it might help to standardize on that.

**Comment by MoOx** [comment]
PR welcome :)

**Comment by rybon** [comment]
#73 here you go. Could you help me out with adding test cases?

**Comment by rybon** [comment]
@MoOx any feedback?
