### ISSUE TITLE
Only works for relative paths if going backwards

### ISSUE THREAD

**Issue by DominicTobias** [postcss/postcss-url#75]
Hi,

Thanks I just installed this plugin and it works (using no custom config and webpack and url-resolver too), however it only works if the path is backward e.g.

    ../fonts/<blah>

It fails to find any paths from the current directory e.g.

    ./fonts/<blah>

I get this exception which is cryptic but happens when a path isn't found:

```
<...>/node_modules/loader-runner/lib/LoaderRunner.js:90
			throw e;
			^

TypeError: Cannot read property '<...>/node_modules/extract-text-webpack-plugin' of null
...
```

Ever encountered this before? Thanks

**Comment by MoOx** [comment]
Not really, this looks weird. I have no idea.
This should works with local path.

**Comment by DominicTobias** [comment]
The issue was that webpack didn't have a context of where the relative paths were that were being referred to in modules in node_modules (we're importing postcss from node_modules, not vanilla css).

We had to override the url function (thanks for providing that) and strip out the relative pathing to module files:

```js
const nodeModulesPrefix = 'node_modules/';

postCSSUrl({
      url(url, decl, from, dirname/* , to, options*/) {
        /* eslint no-console: 0 */
        if (url[0] === '.') {
          const resolvedPath = path.resolve(dirname, url);
          const nodeModuleIndex = resolvedPath.lastIndexOf(nodeModulesPrefix);

          if (nodeModuleIndex !== -1) {
            return resolvedPath.substring(nodeModuleIndex + nodeModulesPrefix.length);
          }
        }

        return url;
      },
    }),
``
