### ISSUE TITLE
⚠️🚨 LOOKING FOR A MAINTAINER 🚨⚠️

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-url#79]
I don't have much time to handle this and I don't even use this module.
Help is appreciated.

**Comment by thisconnect** [comment]
What do you use instead? 
I am using postcss-import and postcss-copy and am pretty happy.

**Comment by MoOx** [comment]
I don't use postcss that much but that's another story :) (I mostly write inline styles via react-native-web)

**Comment by thisconnect** [comment]
thanks interesting, I just browsed through the storybook (I love the storybook project).

![screen shot 2016-10-24 at 2 57 34 pm](https://cloud.githubusercontent.com/assets/546900/19646570/4bfe2190-99fa-11e6-9d92-73c7b1e13099.png)

**Comment by stevenvachon** [comment]
@MoOx you don't even use cssnext?

**Comment by sergcen** [comment]
@MoOx Hi, I could continue maintaining of the project. We plans to using it for some our projects. My npm same **sergcen**.

**Comment by stevenvachon** [comment]
I was also thinking of taking it over, since I also maintain [posthtml-urls](https://github.com/posthtml/posthtml-urls) and [relateurl](https://github.com/stevenvachon/relateurl). Not sure if I will have the time, though, and hadn't communicated this thought.

**Comment by MoOx** [comment]
@sergcen you are now admin here and on npm :) Feel free to do whatever you want here now, you are the boss!

**Comment by IonicaBizau** [comment]
@MoOx I'm also using `postcss-url` in a project and I would love to help when I can (not sure how much time I will have).

**Comment by sergcen** [comment]
Hi, @IonicaBizau . Currently i'm maintainer postcss-url, but you can send PR's to help)

**Comment by IonicaBizau** [comment]
Sure! :grin:
