### ISSUE TITLE
How to get the absolute filename when using the url as callback?

### ISSUE THREAD

**Issue by IonicaBizau** [postcss/postcss-url#82]
The closest I can think of is to do `path.resolve` using these:

```js
> console.log(arguments[1].value, arguments[3])
< url(../fonts/glyphicons-halflings-regular.eot) /home/.../stylesheets/homepage
```

Is there a better solution?

**Comment by sergcen** [comment]
in version 6 you can get this from asset.absolutePath (arguments[0].absolutePath)
